### ISSUE TITLE
알고 풀이 제출 시에 글 특수표시(?) 기능도 추가되면 좋을 것 같습니다!

### ISSUE THREAD

**Issue by LeeHyungGeol** [Voyager003/algo_bot#11]
1. 알고 풀이 제출 시에 제출 sheet 에는 command + B (굵게), command + shift + c (코드) 와 같은 글 특수 표시와 같은 기능들도 추가되면 더 좋을 것 같습니다!

<img width="500" alt="스크린샷 2024-12-24 오후 9 14 13" src="https://github.com/user-attachments/assets/a16f1c84-a3f5-421c-b1aa-514603c18d73" />

<img width="527" alt="스크린샷 2024-12-24 오후 9 19 21" src="https://github.com/user-attachments/assets/7d3adaf3-b0f6-4ee9-b2dd-6082e9109fcd" />

**Comment by LeeHyungGeol** [comment]
혹시 위의 2가지 사항이 issue 에는 적합하지 않은 사항들이라면 바로 삭제하겠습니다!🙇🏻

**Comment by Voyager003** [comment]
안녕하세요 형걸님. 

1. 풀이 과정 부분 생략
https://github.com/geultto/daily-solvetto/pull/168
이게 제출하신 문제의 링크같은데요, 풀이 과정 부분의 생략은 어느 부분이 생략되었다는 것인지 알려주시겠어요?

2. 알고리즘 풀이 제출의 modal 안에서 
텍스트를 command + B (굵게), command + shift + c (코드) 로 만드는 기능을 의도하시는게 맞을까요?

**Comment by LeeHyungGeol** [comment]
안녕하세요 원기님!
1. 앗 죄송합니다. 제가 잘못 봤었나봐요.. 풀이과정 부분 생략된 것 없습니다. 저 부분은 제가 지우도록 하겠습니다.
2. 넵 맞습니다. slack 모달이긴 하지만 혹시나 하여 여기다가 이슈 등록했습니다. 굵게, 코드 뿐만이 아닌 링크, 기울임 등 모달 안에 글 편집 기능들이 추가되면 좋을 것 같습니다.

**Comment by Voyager003** [comment]
아 넵 형걸님 방법이 있으면 적용하고, 없다면 이슈에 공지드리겠습니다!

알고봇에 관심가져주셔서 감사합니다~

**Comment by Voyager003** [comment]
@LeeHyungGeol 
안녕하세요 형걸님. 모달 내에서 글의 텍스트를 편집할 수 있는 기능은 Slack Bolt에서 지원을하지 않아서 물리적으로 불가능할 것 같습니다 ㅜㅜ.  
감사합니다.

**Comment by LeeHyungGeol** [comment]
@Voyager003 
안녕하세요 원기님. 제가 이메일 확인을 늦게 해서 이제야 코멘트 내용을 봤습니다ㅠㅠ

> 모달 내에서 글의 텍스트를 편집할 수 있는 기능은 Slack Bolt에서 지원을하지 않아서 물리적으로 불가능할 것 같습니다 ㅜㅜ

넵 내용 확인했습니다. 그럼 이 이슈는 제가 close 하도록 하겠습니다!
