### ISSUE TITLE
문제 제출 폼에서 "디렉토리명" 항목을 "영문이름"항목으로 대체해주세요.

### ISSUE THREAD

**Issue by bbbjihan** [Voyager003/algo_bot#2]
디렉토리명은 레포지토리 컨벤션에 따라
<영문이름>/<언어>/<문제명>
으로 작성되기 때문에, 디렉토리명보다는 영문이름만 받아도 충분할 것 같습니다.

**Comment by Voyager003** [comment]
반영했습니다!
