### ISSUE TITLE
알고봇 풀이 제출을 통해 생성된 리뷰 PR은, `review required` 라벨을 붙여주세요.

### ISSUE THREAD

**Issue by bbbjihan** [Voyager003/algo_bot#6]
알고봇 풀이 제출을 통해 생성된 리뷰 PR은, `review required` 라벨을 붙여주세요.
레포지토리로의 다른 PR과 구분이 힘들 수 있어 보입니다.

**Comment by bbbjihan** [comment]
<img width="526" alt="image" src="https://github.com/user-attachments/assets/d92da6d4-0914-4d7e-bd0b-b06e1fb52a8f" />

**Comment by Voyager003** [comment]
반영 완료했습니다~
