### ISSUE TITLE
문제 풀이 결과 슬랙 메시지를 업그레이드해주세요!

### ISSUE THREAD

**Issue by bbbjihan** [Voyager003/algo_bot#8]
리뷰를 요청하지 않은 메시지에도 해당 코드에 대한 깃허브 URL과 제출시 입력한 문제 링크를 제공하면 좋을 것 같습니다.

이에 아래와 같이 메시지 폼 변경을 제안드립니다.

```
@<제출자> 님이 오늘의 풀이를 공유해주셨어요. (<파일 링크>)
[<언어>] <문제이름> (<문제 링크>)
:말풍선: “<제출 코멘트>”
:흰색_확인_표시: 리뷰도 함께 부탁하셨어요.(<PR 링크>)
```
<파일 링크>:
1. review required인 경우 머지되지 않았으므로 forked repository에서의 제출 코드 링크를 물려도 될 것 같고, PR 링크를 띄워도 될 것 같습니다.
2. review required가 아닌 경우 upstream 레포지토리에 제출된 코드 링크를 제공

<문제 링크>:
알고봇 풀이 제출 시에 입력한 문제 링크

<PR 링크>:
review PR에 대한 링크

**Comment by bbbjihan** [comment]
슬랙 메시지에 링크를 포함하면 미리보기 카드가 생성되는데, 세로 길이가 너무 길고 제거할 수 없어서 프로토콜을 제거하여 띄우도록 하고 있습니다. 하지만 이 경우에는 문자열에 URL을 임베드할 수 없다.는 side effect가 있습니다.

만약 해당 이슈의 요청사항과 같이 수정된다면, 메시지에는 총 3개의 링크가 생기게 되는데요.

[슬랙 공식문서: 링크 공유 및 미리보기 환경설정 지정](https://slack.com/intl/ko-kr/help/articles/204399343-%EB%A7%81%ED%81%AC-%EA%B3%B5%EC%9C%A0-%EB%B0%8F-%EB%AF%B8%EB%A6%AC%EB%B3%B4%EA%B8%B0-%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95-%EC%A7%80%EC%A0%95)에서 `메시지에 4개가 넘는 링크가 포함된 경우. 링크가 5개를 넘으면 더 펼쳐지지 않습니다.`라는 내용을 확인할 수 있습니다. 리뷰를 요청하거나/요청하지 않은 메시지에 최대한 링크를 많이 걸어서 5개가 넘어가면, 프로토콜을 추가하고 문자열에 URL을 임베드해서 더 보기 좋은 메시지를 만들 수 있지 않을까 합니다.

이를 위해서 hacky한 방식으로 공백에 링크를 건 문자열을 여러 개 추가하거나, 한 문장에 대해서 글자별로 링크를 걸어서 미리보기 카드가 생성되지 않도록 하는 것도 방법이라고 생각합니다.

**Comment by Voyager003** [comment]
메시지 폼 변경 건은 적용했는데 
`메시지에 4개가 넘는 링크가 포함된 경우. 링크가 5개를 넘으면 더 펼쳐지지 않습니다.` -> 이게 실제로 적용되지 않습니다.
그래서 프로토콜을 지운 링크 형식으로 유지한 상태로 메시지 폼 변경 건을 적용했습니다.
추가적으로 행여나 풀었던 문제를 다시 제출할 경우를 우려하여 파일명에 타임스탬프를 명시하도록 수정했습니다.

링크 관련 사진은 DM으로 보내놓을테니 한 번 확인해보심이 좋을 것 같아요.

-적용 완료-
