### ISSUE TITLE
알고풀이 제출 시 `영어 이름` 항목의 의미가 모호한 것 같습니다

### ISSUE THREAD

**Issue by gamamoe** [Voyager003/algo_bot#9]
![image](https://github.com/user-attachments/assets/da177bcd-ea4b-4005-a880-f6ae814c387c)

아마 원래 의도는 개인별 디렉터리 이름 (e.g., Geunho, RimWongi, ...)를 의도한 것 같으나 위 그림처럼 다르게 이해해서 제출되어 저장소의 컨벤션과는 다른 형태로 코드가 커밋되는 경우가 있는 것 같습니다.

영어 이름 대신 `사용자 폴더 이름` 또는 예시를 같이 제시해주는 것이 어떨까요? 

- 영어 이름 (예시: Geunho, RimWongi)

또는

- 사용자 폴더 이름 (예시: Geunho, RimWongi)

**Comment by Voyager003** [comment]
안녕하세요. 근호님 좋은 피드백 너무 감사합니다.

제의해주셨던 이슈를 적용하여 소문자 디렉토리가 추가되었는데요, 원래 지한님과 상의하여 소문자 디렉토리로 통합하는 작업이 계획되어있었는데 시간 이슈로 인해 잠시 미뤄졌습니다.

오늘 밤에 제가 디렉토리를 확인하여 통합하는 작업을 진행해보도록 할 예정이구요(공지 예정), 이슈에서 말씀하신대로 예시 설명도 오늘 밤에 적용해보도록 하겠습니다.

알고봇 서비스에 관심 가져주셔서 감사합니다.

**Comment by Voyager003** [comment]
이슈 적용 완료했습니다.
